export enum Codes {
  NON_EXISTENT_ADMIN_USER = "NON_EXISTENT_ADMIN_USER",
  PASSWORD_MISMATCH = "PASSWORD_MISMATCH",
  ENCRYPTION_FAILED = "ENCRYPTION_FAILED",
  ACCOUNT_UNCLAIMED = "ACCOUNT_UNCLAIMED",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  NO_ACTIVE_VERIFICATION_CODE = "NO_ACTIVE_VERIFICATION_CODE",
  INVALID_VERIFICATION_CODE = "INVALID_VERIFICATION_CODE",
  VERIFICATION_CODE_EXPIRED = "VERIFICATION_CODE_EXPIRED",
}
